import { bufferToBase64url, base64urlToBuffer } from './signing'

const OAEP_ALGO: RsaHashedKeyGenParams = {
  name: 'RSA-OAEP',
  modulusLength: 2048,
  publicExponent: new Uint8Array([1, 0, 1]),
  hash: 'SHA-256',
}

/**
 * Generates the RSA-OAEP keypair.
 * Used ONLY for wrapping and unwrapping the AES-GCM room key.
 * Generated by owners and moderators. Guests do not have this keypair.
 */
export async function generateOaepKeyPair(): Promise<CryptoKeyPair> {
  return crypto.subtle.generateKey(OAEP_ALGO, true, ['encrypt', 'decrypt'])
}

export async function exportOaepKey(key: CryptoKey, type: 'public' | 'private'): Promise<string> {
  const fmt = type === 'public' ? 'spki' : 'pkcs8'
  return bufferToBase64url(await crypto.subtle.exportKey(fmt, key))
}

export async function importOaepPublicKey(b64: string): Promise<CryptoKey> {
  return crypto.subtle.importKey('spki', base64urlToBuffer(b64), OAEP_ALGO, true, ['encrypt'])
}

export async function importOaepPrivateKey(b64: string): Promise<CryptoKey> {
  return crypto.subtle.importKey('pkcs8', base64urlToBuffer(b64), OAEP_ALGO, true, ['decrypt'])
}

/**
 * Wraps the AES-GCM room key with a moderator's RSA-OAEP public key.
 * Called by the owner in Round 4 of the admission handshake.
 */
export async function wrapRoomKey(roomKey: CryptoKey, oaepPublicKey: CryptoKey): Promise<string> {
  const rawKey  = await crypto.subtle.exportKey('raw', roomKey)
  const wrapped = await crypto.subtle.encrypt({ name: 'RSA-OAEP' }, oaepPublicKey, rawKey)
  return bufferToBase64url(wrapped)
}

/**
 * Unwraps the AES-GCM room key using this moderator's RSA-OAEP private key.
 * Called by a moderator after receiving the wrapped key from the owner.
 */
export async function unwrapRoomKey(wrappedKeyB64: string, oaepPrivateKey: CryptoKey): Promise<CryptoKey> {
  const wrapped = base64urlToBuffer(wrappedKeyB64)
  const rawKey  = await crypto.subtle.decrypt({ name: 'RSA-OAEP' }, oaepPrivateKey, wrapped)
  return crypto.subtle.importKey('raw', rawKey, { name: 'AES-GCM' }, true, ['encrypt', 'decrypt'])
}
